---
title: "Lecture 7 (VIA + EDA)"
author: "CJ Snyder"
date: "9/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

# Linking National Weather Data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

# Create a _ggplot_
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point()

weather_df %>% 
  ggplot(aes(x=tmin, y=tmax)) + geom_point()
# Different way to produce the same ggplot
```

# Saving Plots - does not print the scatterplot directly
```{r}
scatterplot = 
  weather_df %>% 
  ggplot(aes(x=tmin, y=tmax)) + geom_point()

scatterplot
# Prints saved scatterplot
```

# Adding color
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax)) + 
  geom_point(aes(color = name), alpha = .4)
```

## Why aesthetic positions matter??
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax)) + 
  geom_point(aes(color = name), alpha = .4) +
  geom_smooth(se = FALSE)

weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name)) + 
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)
# color is applied to the ENTIRE scatterplor, rather than JUST to the data points
```

# Splitting _facets_ up scatterplot groupings
```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name)) + 
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE) +
  facet_grid(~ name)
```

# NEW PLOT - temp over time
```{r}
weather_df %>% 
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point(aes(size=prcp), alpha = .5) +
  geom_smooth(se=FALSE) +
  facet_grid(~ name)
# Points should get bigger/smaller depending on amount of prcp

weather_df %>% 
  ggplot(aes(x=date, y=prcp, color=name)) +
  geom_point() +
  geom_smooth(se=FALSE)
```






