---
title: "Lecture 9 (VIZ + EDA III)"
author: "CJ Snyder"
date: "10/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
```

# Importing NOAA Dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

# _group_by_ & _summarize_ Functions
Doesn't change your dataset permanently. However, the group can still be present in the background for use at a later time (it can also causes issues when doing future analyses).

Can _ungroup_ anything that was put into a group.
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs=n())

weather_df %>% 
  group_by(name) %>% 
  summarize(n_obs=n())

weather_df %>% 
  group_by(month) %>% 
  summarize(n_obs=n())
```


```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(n_obs=n(), n_unique=n_distinct(date))
```

## Alternative ways to _count_...
```{r}
weather_df %>% 
  count(name)

weather_df %>% 
  count(month)

weather_df %>% 
    count(name, month)
```


```{r}

```


